# Generated by Django 2.2.5 on 2020-08-15 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200815_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')])),
                ('description', models.CharField(max_length=200, verbose_name='人物描述')),
                ('is_delete', models.BooleanField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookInfo')),
            ],
            options={
                'verbose_name': '人物列表',
                'db_table': 'peopleinfo',
            },
        ),
    ]
