# Generated by Django 2.2.5 on 2020-08-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_peopleinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='commentcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='readcount',
            field=models.IntegerField(default=0),
        ),
    ]
